import type { Metadata } from "next";
import { TikTok_Sans } from "next/font/google"
import "./globals.css";

import { Header } from "./components/Header";
import { Footer } from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tiktokSans = TikTok_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  fallback: ["system-ui", "sans-serif"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tiktokSans.className}>
        <Header />
        <main className="w-full max-w-md">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
